name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Clean project
      run: mvn clean

    - name: Build project
      run: mvn install

    - name: Deploy WAR to Tomcat
      env:
        TOMCAT_USER: admin
        TOMCAT_PASS: admin
        TOMCAT_HOST: 34.207.95.255
        TOMCAT_PORT: 8081
      run: |
        curl --upload-file webapp/target/webapp.war "http://${TOMCAT_USER}:${TOMCAT_PASS}@${TOMCAT_HOST}:${TOMCAT_PORT}/manager/text/deploy?path=/&update=true"
